version: "3.7"

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
    - partd:/data/db
    restart: unless-stopped
      
  server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"

  client:
    build: ./client
    container_name: client_container
    environment:
      REACT_APP_SERVER_PORT: 8000
      NODE_PATH: src
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start

volumes:
  partd: